### Pandas practice notebook

In [1]:
import pandas as pd
import numpy as np

In [5]:
# first operation in pandas
wine = pd.read_csv("/home/paulami/programming/daily_python_practice/python_project/winequality-red.csv")
wine.head()   # show first 5 rows
# wine.tail()   # last 5 rows
# wine.sample(10) # random 10 rows

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [ ]:
# wine.describe()  # make summary of each col
# wine.loc[rows,columns]
wine.loc[:10, ["citric acid","chlorides"]]  #accessing data frame
wine.iloc[:10,0:5]

In [ ]:
# filtering data
wine[wine['fixed acidity']>10][['fixed acidity', 'residual sugar']]
# for multiple filter use & operator

In [ ]:
# adding / removing cols
# wine.info()
wine['price'] = np.where(wine['alcohol']>9.5,10,7)  # adding a col
wine.drop(columns=['fixed acidity']) # removing a col

# converting date time
dataframe['new date col'] = pd.to_datetime(dataframe['col want to change'])

In [3]:
mydata = pd.DataFrame()
mydata['age'] = pd.Series([12,32,25,96])
mydata['height'] = pd.Series([151,198,188,190])
mydata['location'] = pd.Series(['kolkata','mumbai','delhi','kunnur'])
mydata['price'] = 150
mydata.head()

   age  height location  price
0   12     151  kolkata    150
1   32     198   mumbai    150
2   25     188    delhi    150
3   96     190   kunnur    150