In [2]:
import numpy as np
import pandas as pd

### Day 1 — Bird Diversity & Habitat Analysis

In [44]:
np.random.seed(42)

sites = ["East Kolkata Wetlands", "Sundarban Fringe", "Nalban", "Santragachi"]
species = ["Egret", "Kingfisher", "Heron", "Cormorant", "Ibis", "Pied Hornbill"]

dates = pd.date_range("2025-01-01", "2025-06-01", freq="MS")

rows = []

for date in dates:
    for site in sites:
        for sp in species:
            rows.append({
                "date": date,
                "site": site,
                "species": sp,
                "count": np.random.poisson(
                    np.random.uniform(5, 30)
                ),
                "observation_hours": np.random.uniform(2, 8)
            })

birds = pd.DataFrame(rows)

# Introduce some missing observations
missing_idx = np.random.choice(
    birds.index,
    size=12,
    replace=False
)

birds.loc[missing_idx, "count"] = np.nan

birds.head()

        date                   site     species  count  observation_hours
0 2025-01-01  East Kolkata Wetlands       Egret   15.0           2.935967
1 2025-01-01  East Kolkata Wetlands  Kingfisher    6.0           3.090950
2 2025-01-01  East Kolkata Wetlands       Heron    9.0           3.198043
3 2025-01-01  East Kolkata Wetlands   Cormorant   19.0           5.645269
4 2025-01-01  East Kolkata Wetlands        Ibis    8.0           4.971061

In [ ]:
birds.info()
birds.describe()

In [ ]:
birds['count'].unique()
birds[birds['count'].isna()]
birds.fillna(birds['count'].mean(), inplace=True)

In [64]:
birds['month'] = birds['date'].dt.month
birds['day_name'] = birds['date'].dt.day_name()
birds['density'] = birds['count'] / birds['observation_hours']
birds.head()

,date,site,species,count,observation_hours,month,day_name,density
0,2025-01-01,East Kolkata Wetlands,Egret,15.0,2.935967,1,Wednesday,5.109049
1,2025-01-01,East Kolkata Wetlands,Kingfisher,6.0,3.090950,1,Wednesday,1.941151
2,2025-01-01,East Kolkata Wetlands,Heron,9.0,3.198043,1,Wednesday,2.814221
3,2025-01-01,East Kolkata Wetlands,Cormorant,19.0,5.645269,1,Wednesday,3.365650
4,2025-01-01,East Kolkata Wetlands,Ibis,8.0,4.971061,1,Wednesday,1.609314

In [91]:
birds[birds['count']>birds['count'].mean()]
birds.query('species == "Egret" | species =="Kingfisher" | species == "Heron" | species == "Cormorant" | species == "Ibis"').where(birds['count'] > birds['count'].mean()).dropna()

,date,site,species,count,observation_hours,month,day_name,density
3,2025-01-01,East Kolkata Wetlands,Cormorant,19.000000,5.645269,1.0,Wednesday,3.365650
6,2025-01-01,Sundarban Fringe,Egret,34.000000,5.587400,1.0,Wednesday,6.085120
7,2025-01-01,Sundarban Fringe,Kingfisher,19.000000,2.271364,1.0,Wednesday,8.365019
10,2025-01-01,Sundarban Fringe,Ibis,29.000000,2.033133,1.0,Wednesday,14.263702
14,2025-01-01,Nalban,Heron,17.280303,6.564710,1.0,Wednesday,2.632302
15,2025-01-01,Nalban,Cormorant,23.000000,5.136397,1.0,Wednesday,4.477847
22,2025-01-01,Santragachi,Ibis,43.000000,4.983491,1.0,Wednesday,8.628489
27,2025-02-01,East Kolkata Wetlands,Cormorant,17.280303,5.801178,2.0,Saturday,2.978757
31,2025-02-01,Sundarban Fringe,Kingfisher,22.000000,4.046398,2.0,Saturday,5.436934
34,2025-02-01,Sundarban Fringe,Ibis,29.000000,2.608829,2.0,Saturday,11.116097
37,2025-02-01,Nalban,Kingfisher,26.000000,5.945677,2.0,Saturday,4.372925
40,2025-02-01,Nalban,Ibis,18.000000,3.171458,2.0,Saturday,5.675623
43,2025-02-01,Santragachi,Kingfisher,27.000000,5.420367,2.0,Saturday,4.981213
44,2025-02-01,Santragachi,Heron,17.280303,5.009098,2.0,Saturday,3.449784
45,2025-02-01,Santragachi,Cormorant,27.000000,6.774756,2.0,Saturday,3.985383
46,2025-02-01,Santragachi,Ibis,25.000000,2.563892,2.0,Saturday,9.750802
49,2025-03-01,East Kolkata Wetlands,Kingfisher,20.000000,2.512085,3.0,Saturday,7.961515
51,2025-03-01,East Kolkata Wetlands,Cormorant,35.000000,4.453718,3.0,Saturday,7.858603
54,2025-03-01,Sundarban Fringe,Egret,22.000000,4.949695,3.0,Saturday,4.444718
56,2025-03-01,Sundarban Fringe,Heron,22.000000,4.247676,3.0,Saturday,5.179303
57,2025-03-01,Sundarban Fringe,Cormorant,21.000000,5.952162,3.0,Saturday,3.528130
60,2025-03-01,Nalban,Egret,22.000000,2.604668,3.0,Saturday,8.446374
63,2025-03-01,Nalban,Cormorant,17.280303,6.658478,3.0,Saturday,2.595233
64,2025-03-01,Nalban,Ibis,20.000000,4.573964,3.0,Saturday,4.372575
66,2025-03-01,Santragachi,Egret,22.000000,7.373139,3.0,Saturday,2.983804
68,2025-03-01,Santragachi,Heron,30.000000,4.690673,3.0,Saturday,6.395671
70,2025-03-01,Santragachi,Ibis,17.280303,4.966522,3.0,Saturday,3.479357
74,2025-04-01,East Kolkata Wetlands,Heron,17.280303,6.662881,4.0,Tuesday,2.593518
75,2025-04-01,East Kolkata Wetlands,Cormorant,17.280303,2.667185,4.0,Tuesday,6.478855
79,2025-04-01,Sundarban Fringe,Kingfisher,19.000000,7.815815,4.0,Tuesday,2.430968
80,2025-04-01,Sundarban Fringe,Heron,20.000000,4.727246,4.0,Tuesday,4.230793
81,2025-04-01,Sundarban Fringe,Cormorant,22.000000,2.272678,4.0,Tuesday,9.680209
84,2025-04-01,Nalban,Egret,25.000000,7.596371,4.0,Tuesday,3.291045
86,2025-04-01,Nalban,Heron,27.000000,7.819486,4.0,Tuesday,3.452912
87,2025-04-01,Nalban,Cormorant,32.000000,4.488917,4.0,Tuesday,7.128668
90,2025-04-01,Santragachi,Egret,17.280303,2.172696,4.0,Tuesday,7.953392
91,2025-04-01,Santragachi,Kingfisher,26.000000,3.277785,4.0,Tuesday,7.932186
93,2025-04-01,Santragachi,Cormorant,23.000000,7.174182,4.0,Tuesday,3.205940
94,2025-04-01,Santragachi,Ibis,29.000000,4.754815,4.0,Tuesday,6.099081
97,2025-05-01,East Kolkata Wetlands,Kingfisher,17.280303,2.245212,5.0,Thursday,7.696514
99,2025-05-01,East Kolkata Wetlands,Cormorant,20.000000,6.796462,5.0,Thursday,2.942707
100,2025-05-01,East Kolkata Wetlands,Ibis,29.000000,3.661266,5.0,Thursday,7.920758
103,2025-05-01,Sundarban Fringe,Kingfisher,20.000000,3.514622,5.0,Thursday,5.690513
104,2025-05-01,Sundarban Fringe,Heron,30.000000,5.192681,5.0,Thursday,5.777363
109,2025-05-01,Nalban,Kingfisher,31.000000,2.610695,5.0,Thursday,11.874233
112,2025-05-01,Nalban,Ibis,29.000000,3.679875,5.0,Thursday,7.880703
118,2025-05-01,Santragachi,Ibis,40.000000,6.385205,5.0,Thursday,6.264482
120,2025-06-01,East Kolkata Wetlands,Egret,24.000000,6.771604,6.0,Sunday,3.544212
122,2025-06-01,East Kolkata Wetlands,Heron,22.000000,7.263203,6.0,Sunday,3.028967
123,2025-06-01,East Kolkata Wetlands,Cormorant,19.000000,4.261667,6.0,Sunday,4.458350
126,2025-06-01,Sundarban Fringe,Egret,17.280303,7.638993,6.0,Sunday,2.262118
127,2025-06-01,Sundarban Fringe,Kingfisher,18.000000,6.764151,6.0,Sunday,2.661088
128,2025-06-01,Sundarban Fringe,Heron,21.000000,6.731583,6.0,Sunday,3.119623
132,2025-06-01,Nalban,Egret,22.000000,5.035332,6.0,Sunday,4.369126
133,2025-06-01,Nalban,Kingfisher,29.000000,6.179905,6.0,Sunday,4.692629
134,2025-06-01,Nalban,Heron,31.000000,5.457730,6.0,Sunday,5.680017
135,2025-06-01,Nalban,Cormorant,19.000000,7.606202,6.0,Sunday,2.497962
136,2025-06-01,Nalban,Ibis,27.000000,7.909047,6.0,Sunday,3.413812
142,2025-06-01,Santragachi,Ibis,21.000000,5.981224,6.0,Sunday,3.510987

In [85]:
birds.query('species == "Egret"')

,date,site,species,count,observation_hours,month,day_name,density
0,2025-01-01,East Kolkata Wetlands,Egret,15.000000,2.935967,1,Wednesday,5.109049
6,2025-01-01,Sundarban Fringe,Egret,34.000000,5.587400,1,Wednesday,6.085120
12,2025-01-01,Nalban,Egret,5.000000,3.865894,1,Wednesday,1.293362
18,2025-01-01,Santragachi,Egret,12.000000,2.660312,1,Wednesday,4.510750
24,2025-02-01,East Kolkata Wetlands,Egret,8.000000,7.449595,2,Saturday,1.073884
30,2025-02-01,Sundarban Fringe,Egret,12.000000,6.145626,2,Saturday,1.952608
36,2025-02-01,Nalban,Egret,13.000000,3.952398,2,Saturday,3.289142
42,2025-02-01,Santragachi,Egret,13.000000,3.016956,2,Saturday,4.308978
48,2025-03-01,East Kolkata Wetlands,Egret,3.000000,5.133460,3,Saturday,0.584401
54,2025-03-01,Sundarban Fringe,Egret,22.000000,4.949695,3,Saturday,4.444718
60,2025-03-01,Nalban,Egret,22.000000,2.604668,3,Saturday,8.446374
66,2025-03-01,Santragachi,Egret,22.000000,7.373139,3,Saturday,2.983804
72,2025-04-01,East Kolkata Wetlands,Egret,13.000000,6.205815,4,Tuesday,2.094810
78,2025-04-01,Sundarban Fringe,Egret,12.000000,3.341575,4,Tuesday,3.591121
84,2025-04-01,Nalban,Egret,25.000000,7.596371,4,Tuesday,3.291045
90,2025-04-01,Santragachi,Egret,17.280303,2.172696,4,Tuesday,7.953392
96,2025-05-01,East Kolkata Wetlands,Egret,5.000000,2.768275,5,Thursday,1.806179
102,2025-05-01,Sundarban Fringe,Egret,14.000000,4.213482,5,Thursday,3.322668
108,2025-05-01,Nalban,Egret,8.000000,4.136580,5,Thursday,1.933965
114,2025-05-01,Santragachi,Egret,14.000000,5.663720,5,Thursday,2.471873
120,2025-06-01,East Kolkata Wetlands,Egret,24.000000,6.771604,6,Sunday,3.544212
126,2025-06-01,Sundarban Fringe,Egret,17.280303,7.638993,6,Sunday,2.262118
132,2025-06-01,Nalban,Egret,22.000000,5.035332,6,Sunday,4.369126
138,2025-06-01,Santragachi,Egret,7.000000,6.817121,6,Sunday,1.026826